import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '../context/AuthProvider'
import { MealSiteProvider } from '@/components/mealSiteProvider/MealSiteProvider'
import Header from '../components/header/Header'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <MealSiteProvider>
          <body className={inter.className}>
            <Header/>
              {children}
          </body>
        </MealSiteProvider>
      </AuthProvider>
    </html>
  )
}
